const { test, expect } = require('./electron.fixture');
const { execFile } = require('node:child_process');
const { promisify } = require('node:util');
const fs = require('node:fs/promises');

const run = promisify(execFile);
const ffmpeg = process.env.SRT_FFMPEG_PATH || '/opt/homebrew/opt/ffmpeg-full/bin/ffmpeg';
const ffprobe = process.env.SRT_FFPROBE_PATH || '/opt/homebrew/opt/ffmpeg-full/bin/ffprobe';

async function makeVideo(file, width, height, duration) {
  await run(ffmpeg, ['-v', 'error', '-y', '-f', 'lavfi', '-i',
    `color=c=0x304860:s=${width}x${height}:r=24,drawbox=x=40:y=30:w=160:h=100:color=0xD05030:t=fill`,
    '-f', 'lavfi', '-i', 'sine=frequency=440:sample_rate=48000', '-t', String(duration),
    '-c:v', 'libx264', '-crf', '9', '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-shortest', file]);
}

async function enterHome(window) {
  await window.getByTestId('local-cli-codex').click();
  await window.getByTestId('continue').click();
  await expect(window.getByTestId('home-page')).toBeVisible();
}

async function openProject(window, source) {
  await window.getByTestId('video-input').setInputFiles(source);
  await window.getByTestId('start-editing').click();
  await expect(window.getByTestId('editor-page')).toBeVisible();
  await window.waitForFunction(() => window.projectEditingState === 'ready'
    && document.getElementById('previewVideo').readyState >= 2);
}

async function submit(window, text, instruction = 'success', timeline = 'success') {
  await window.locator('.input-editor').fill(text);
  await window.locator('#generateBtn').click();
  const card = window.getByTestId('request-status-card').last();
  await expect(card.getByTestId('instruction-status')).toHaveAttribute('data-state', instruction);
  await expect(card.locator('[data-testid="timeline-status"], [data-testid="subtitle-status"]'))
    .toHaveAttribute('data-state', timeline);
  return card;
}

async function saveSkill(window, card, { name, intent, preferences }) {
  await card.getByTestId('request-status-summary').click();
  await card.getByTestId('save-as-skill').click();
  const dialog = window.getByTestId('skill-save-dialog');
  await expect(dialog).toBeVisible();
  await dialog.getByTestId('skill-name').fill(name);
  await expect(dialog.getByTestId('skill-intent')).not.toHaveValue('');
  await dialog.getByTestId('skill-intent').fill(intent);
  await dialog.getByTestId('skill-preferences').fill(preferences);
  await dialog.getByTestId('skill-save').click();
  await expect(dialog).toBeHidden();
}

async function useOnlySkill(window) {
  await window.getByTestId('personal-skills-button').click();
  const item = window.getByTestId('personal-skill-item');
  await item.getByTestId('skill-use').click();
  await expect(window.getByTestId('personal-skills-dialog')).toBeHidden();
  await expect(window.getByTestId('selected-skill')).toBeVisible();
  await expect(window.locator('.input-editor')).toBeFocused();
}

test.describe('personal skill desktop behavior (local deterministic fixture, not real AI)', () => {
  test.skip(!process.env.SRT_REAL_EXPORT, 'requires synthetic playable media generated by actual FFmpeg');
  test.use({ localCliMode: 'two', localCliEffectResult: 'personal-skill-transactions' });

  test('official template is selectable without writing personal storage or applying an old recipe', async ({ window }, testInfo) => {
    const video = testInfo.outputPath('official.mp4');
    await makeVideo(video, 640, 360, 4);
    await enterHome(window);
    await openProject(window, video);
    const before = await window.evaluate(() => localStorage.getItem(STORAGE_KEYS.PERSONAL_SKILLS));
    await window.getByTestId('personal-skills-button').click();
    const item = window.getByTestId('official-skill-item');
    await expect(item).toContainText('官方模板');
    await expect(item.getByTestId('skill-delete')).toHaveCount(0);
    await item.getByTestId('skill-view').click();
    await expect(item).toContainText('粉色');
    await item.getByTestId('skill-use').click();
    await expect(window.getByTestId('selected-skill')).toContainText('口播要点自动卡片');
    await expect(window.getByTestId('request-status-card')).toHaveCount(0);
    expect(await window.evaluate(() => localStorage.getItem(STORAGE_KEYS.PERSONAL_SKILLS))).toBe(before);
  });

  test('explicit save is editable, global across projects, isolated from project state, and safely deletable', async ({ window }, testInfo) => {
    const landscape = testInfo.outputPath('skill-bank-landscape.mp4');
    const portrait = testInfo.outputPath('skill-bank-portrait.mp4');
    await makeVideo(landscape, 640, 360, 4);
    await makeVideo(portrait, 360, 640, 3);
    await enterHome(window);
    await openProject(window, landscape);

    await window.getByTestId('personal-skills-button').click();
    await expect(window.getByTestId('personal-skill-item')).toHaveCount(0);
    await window.getByTestId('personal-skills-dialog').getByRole('button', { name: '关闭', exact: true }).click();

    const card = await submit(window, '先做一个弹入重点卡片');
    const afterEdit = await window.evaluate(() => projectEditing.load(getActiveProjectId()));
    const projectBytes = await window.evaluate(() => localStorage.getItem(STORAGE_KEYS.PROJECT_EDIT_STATE));
    const projectId = afterEdit.document.projectId;
    await saveSkill(window, card, {
      name: '<重点卡片>',
      intent: '突出用户提到的重点，并适配当前画面',
      preferences: '暖色矩形、白字、轻微弹入'
    });
    expect(await window.evaluate(() => localStorage.getItem(STORAGE_KEYS.PROJECT_EDIT_STATE))).toBe(projectBytes);
    expect(await window.evaluate(() => projectEditing.load(getActiveProjectId()))).toEqual(afterEdit);

    await window.getByTestId('personal-skills-button').click();
    const item = window.getByTestId('personal-skill-item');
    await expect(item).toHaveCount(1);
    await item.getByTestId('skill-view').click();
    await expect(item).toContainText('<重点卡片>');
    await expect(item).toContainText('突出用户提到的重点，并适配当前画面');
    await expect(item).toContainText('暖色矩形、白字、轻微弹入');
    await expect(item).toContainText('动画图层');
    await expect(item).not.toContainText('referenceRecipe');
    const bankScreenshot = await bankDialogScreenshot(window, testInfo, 'personal-skills-bank.png');
    await testInfo.attach('personal-skills-bank', { body: bankScreenshot, contentType: 'image/png' });
    await window.getByTestId('personal-skills-dialog').getByRole('button', { name: '关闭', exact: true }).click();

    await card.getByTestId('save-as-skill').click();
    await window.getByTestId('skill-name').fill('  <重点卡片>  ');
    await window.getByTestId('skill-save').click();
    await expect(window.getByTestId('skill-save-dialog')).toBeVisible();
    await expect(window.getByTestId('skill-save-dialog')).toContainText('已有同名技能');
    await window.getByTestId('skill-cancel').click();

    const skillBytes = await window.evaluate(() => {
      const original = Storage.prototype.setItem;
      window.__restoreSkillSetItem = function() { Storage.prototype.setItem = original; };
      Storage.prototype.setItem = function(key, value) {
        if (key === STORAGE_KEYS.PERSONAL_SKILLS) throw new DOMException('quota', 'QuotaExceededError');
        return original.call(this, key, value);
      };
      return localStorage.getItem(STORAGE_KEYS.PERSONAL_SKILLS);
    });
    await card.getByTestId('save-as-skill').click();
    await window.getByTestId('skill-name').fill('不会写入');
    await window.getByTestId('skill-save').click();
    await expect(window.getByTestId('skill-save-dialog')).toBeVisible();
    await expect(window.getByTestId('skill-save-dialog')).toContainText('暂时无法保存');
    expect(await window.evaluate(() => localStorage.getItem(STORAGE_KEYS.PERSONAL_SKILLS))).toBe(skillBytes);
    await window.evaluate(() => window.__restoreSkillSetItem());
    await window.getByTestId('skill-cancel').click();

    await window.reload();
    await window.waitForFunction(() => window.projectEditingState === 'ready');
    await window.getByTestId('personal-skills-button').click();
    await expect(window.getByTestId('personal-skill-item')).toHaveCount(1);
    expect(await window.evaluate(() => projectEditing.load(getActiveProjectId()))).toEqual(afterEdit);
    await window.getByTestId('personal-skills-dialog').getByRole('button', { name: '关闭', exact: true }).click();

    await window.locator('.wtab.is-pinned .wtab__main').click();
    await openProject(window, portrait);
    const otherBefore = await window.evaluate(() => projectEditing.load(getActiveProjectId()));
    expect(otherBefore.document.projectId).not.toBe(projectId);
    await window.getByTestId('personal-skills-button').click();
    await expect(window.getByTestId('personal-skill-item')).toHaveCount(1);
    await window.getByTestId('personal-skill-item').getByTestId('skill-use').click();
    await expect(window.getByTestId('selected-skill')).toBeVisible();
    expect(await window.evaluate(() => projectEditing.load(getActiveProjectId()))).toEqual(otherBefore);
    await window.getByTestId('personal-skills-button').click();
    window.once('dialog', dialog => dialog.accept());
    await window.getByTestId('personal-skill-item').getByTestId('skill-delete').click();
    await expect(window.getByTestId('personal-skill-item')).toHaveCount(0);
    await expect(window.getByTestId('selected-skill')).toBeHidden();
    expect(await window.evaluate(() => projectEditing.load(getActiveProjectId()))).toEqual(otherBefore);
    expect(await window.evaluate(() => {
      const stored = JSON.parse(localStorage.getItem(STORAGE_KEYS.PERSONAL_SKILLS));
      return stored.skills.length;
    })).toBe(0);
  });

  test('selection snapshots through clarify, blocks switching, exits explicitly, and clears on every terminal result', async ({ window, readScenarioState }, testInfo) => {
    const source = testInfo.outputPath('skill-lifecycle.mp4');
    await makeVideo(source, 640, 360, 4);
    await enterHome(window);
    await openProject(window, source);
    const sourceCard = await submit(window, '先做一个弹入重点卡片');
    await saveSkill(window, sourceCard, { name: '重点卡片', intent: '突出重点', preferences: '暖色、白字' });
    expect(await window.evaluate(() => editCapabilityRegistry.promptDefinitions().length)).toBe(8);
    await useOnlySkill(window);
    await sourceCard.getByTestId('subtitle-undo').click();
    await expect(window.getByTestId('selected-skill')).toBeVisible();
    await window.getByTestId('selected-skill-clear').click();
    await expect(sourceCard.getByTestId('save-as-skill')).toHaveCount(0);

    await useOnlySkill(window);
    await expect(window.locator('.input-editor')).toContainText('使用「重点卡片」');
    const clarifyCard = await submit(window, '需要补充', 'clarifying', 'waiting');
    await expect(clarifyCard.getByTestId('save-as-skill')).toHaveCount(0);
    await expect(window.getByTestId('selected-skill')).toBeVisible();
    await expect(window.getByTestId('personal-skills-button')).toBeDisabled();
    await expect(window.getByTestId('skill-exit-clarify')).toBeVisible();
    const beforeFollowup = await window.evaluate(() => projectEditing.load(getActiveProjectId()));
    const derivedCard = await submit(window, '放在画面中央');
    const clarifyCalls = (await readScenarioState()).translationCalls.slice(-2);
    expect(clarifyCalls[0].skill).toEqual(clarifyCalls[1].skill);
    expect((await window.evaluate(() => projectEditing.load(getActiveProjectId()))).document.revision)
      .toBe(beforeFollowup.document.revision + 1);
    await expect(window.getByTestId('selected-skill')).toBeHidden();
    await derivedCard.getByTestId('request-status-summary').click();
    await derivedCard.getByTestId('save-as-skill').click();
    await expect(window.getByTestId('skill-intent')).toHaveValue(/原始意图：突出重点/);
    await expect(window.getByTestId('skill-intent')).toHaveValue(/原始偏好：暖色、白字/);
    await expect(window.getByTestId('skill-intent')).toHaveValue(/需要补充\n放在画面中央/);
    await window.getByTestId('skill-cancel').click();

    await useOnlySkill(window);
    await submit(window, '需要补充', 'clarifying', 'waiting');
    const beforeExit = await window.evaluate(() => projectEditing.load(getActiveProjectId()));
    await window.getByTestId('skill-exit-clarify').click();
    await expect(window.getByTestId('selected-skill')).toBeHidden();
    await expect(window.getByTestId('skill-exit-clarify')).toBeHidden();
    await expect(window.getByTestId('request-status-card').last().getByTestId('save-as-skill')).toHaveCount(0);
    expect(await window.evaluate(() => projectEditing.load(getActiveProjectId()))).toEqual(beforeExit);

    await useOnlySkill(window);
    const beforeMalformed = await window.evaluate(() => localStorage.getItem(STORAGE_KEYS.PROJECT_EDIT_STATE));
    await submit(window, '错误配方', 'success', 'failed');
    expect(await window.evaluate(() => localStorage.getItem(STORAGE_KEYS.PROJECT_EDIT_STATE))).toBe(beforeMalformed);
    await expect(window.getByTestId('selected-skill')).toBeHidden();
    await expect(window.getByTestId('request-status-card').last().getByTestId('save-as-skill')).toHaveCount(0);

    await useOnlySkill(window);
    await window.locator('.input-editor').fill('慢速执行');
    await window.locator('#generateBtn').click();
    await expect(window.getByTestId('personal-skills-button')).toBeDisabled();
    await expect(window.getByTestId('request-status-card').last().getByTestId('timeline-status'))
      .toHaveAttribute('data-state', 'success');
    await expect(window.getByTestId('selected-skill')).toBeHidden();

    await submit(window, '普通请求不带技能');
    await expect(window.getByTestId('selected-skill')).toBeHidden();
    expect((await readScenarioState()).translationCalls.at(-1).skill).toBeUndefined();
    expect(await window.evaluate(() => {
      const records = getProjectConversation(getActiveProjectId());
      return Object.prototype.hasOwnProperty.call(records.at(-1), 'skillContext');
    })).toBe(false);
    await window.evaluate(() => {
      const all = JSON.parse(localStorage.getItem(STORAGE_KEYS.PROJECT_CONVERSATIONS));
      all[getActiveProjectId()] = [];
      localStorage.setItem(STORAGE_KEYS.PROJECT_CONVERSATIONS, JSON.stringify(all));
    });
    await window.reload();
    await window.waitForFunction(() => window.projectEditingState === 'ready');
    await expect(window.getByTestId('request-status-card')).not.toHaveCount(0);
    await expect(window.getByTestId('save-as-skill')).toHaveCount(0);
  });

  test('historical missing capability remains viewable and asks to clarify without project mutation', async ({ window }, testInfo) => {
    const source = testInfo.outputPath('skill-missing-capability.mp4');
    await makeVideo(source, 640, 360, 4);
    await enterHome(window);
    await openProject(window, source);
    await window.evaluate(() => localStorage.setItem(STORAGE_KEYS.PERSONAL_SKILLS, JSON.stringify({
      schemaVersion: 1,
      skills: [{ schemaVersion: 1, id: 'old-skill', name: '旧胶片感', intent: '保留旧效果意图',
        preferences: { description: '柔和一些' },
        referenceRecipe: { kind: 'instruction', steps: [{ capability: 'retired.film@1',
          range: { start: 0, end: 2 }, params: { strength: .5 } }] },
        capabilityVersions: ['retired.film@1'], createdAt: 1, updatedAt: 1 }]
    })));
    const before = await window.evaluate(() => projectEditing.load(getActiveProjectId()));
    await window.getByTestId('personal-skills-button').click();
    await expect(window.getByTestId('personal-skill-item')).toContainText('旧胶片感');
    await window.getByTestId('personal-skill-item').getByTestId('skill-use').click();
    await submit(window, '请适配当前视频', 'clarifying', 'waiting');
    await expect(window.getByTestId('request-clarify')).toContainText('retired.film@1');
    expect(await window.evaluate(() => projectEditing.load(getActiveProjectId()))).toEqual(before);
    await window.getByTestId('skill-exit-clarify').click();
  });
});

test.describe('cross-project skill execution and production export (local fixture, not real AI)', () => {
  test.skip(!process.env.SRT_REAL_EXPORT, 'requires actual FFmpeg export');
  test.use({ realEnvironment: true, localCliMode: 'two', localCliEffectResult: 'personal-skill-transactions' });

  test('re-derives one skill for two media facts and exports a visible playable result with audio', async ({ window, readScenarioState }, testInfo) => {
    const landscape = testInfo.outputPath('skill-landscape-640x360-4s.mp4');
    const portrait = testInfo.outputPath('skill-portrait-360x640-3s.mp4');
    await makeVideo(landscape, 640, 360, 4);
    await makeVideo(portrait, 360, 640, 3);
    await enterHome(window);
    await openProject(window, landscape);
    const sourceCard = await submit(window, '先做一个弹入重点卡片');
    await saveSkill(window, sourceCard, {
      name: '跨项目重点卡片', intent: '突出当前视频里的重点', preferences: '暖色卡片、白字、轻微弹入'
    });
    const savedContext = await window.evaluate(() => SRTPersonalSkills.contextFromSkill(
      SRTPersonalSkills.createPersonalSkillStore({ storage: localStorage,
        storageKey: STORAGE_KEYS.PERSONAL_SKILLS, capabilityRegistry: editCapabilityRegistry }).list()[0]));
    expect(savedContext.referenceRecipe.steps[0].range.end).toBeGreaterThan(3);

    await useOnlySkill(window);
    await submit(window, '把同样的表达用于这个横屏视频');
    const landscapeCall = (await readScenarioState()).translationCalls.at(-1);
    expect(landscapeCall.context.video).toEqual({ durationSeconds: 4, width: 640, height: 360 });
    expect(landscapeCall.skill).toEqual(savedContext);
    const landscapeEdit = (await window.evaluate(() => projectEditing.load(getActiveProjectId()))).document.edits.at(-1);

    await window.locator('.wtab.is-pinned .wtab__main').click();
    await openProject(window, portrait);
    await useOnlySkill(window);
    await submit(window, '把同样的表达用于这个竖屏视频');
    const portraitCall = (await readScenarioState()).translationCalls.at(-1);
    expect(portraitCall.context.video).toEqual({ durationSeconds: 3, width: 360, height: 640 });
    expect(portraitCall.skill).toEqual(savedContext);
    const portraitSnapshot = await window.evaluate(() => projectEditing.load(getActiveProjectId()));
    const portraitEdit = portraitSnapshot.document.edits.at(-1);
    expect(portraitEdit.range.end).toBeLessThanOrEqual(3);
    expect(portraitEdit.range).not.toEqual(landscapeEdit.range);
    expect(portraitEdit.payload).not.toEqual(landscapeEdit.payload);
    await expect(window.locator('.tl-marker[data-lane="visual"]')).toHaveCount(1);
    const visibleRegion = await window.evaluate(() => new Promise(resolve => {
      const video = document.getElementById('previewVideo');
      const sample = () => requestAnimationFrame(() => requestAnimationFrame(() => {
        const canvas = document.getElementById('previewLayerCanvas');
        const context = canvas.getContext('2d');
        const data = context.getImageData(0, 0, canvas.width, canvas.height).data;
        var minX = canvas.width, minY = canvas.height, maxX = -1, maxY = -1;
        for (var y = 0; y < canvas.height; y++) for (var x = 0; x < canvas.width; x++) {
          if (data[(y * canvas.width + x) * 4 + 3] > 10) {
            minX = Math.min(minX, x); minY = Math.min(minY, y);
            maxX = Math.max(maxX, x); maxY = Math.max(maxY, y);
          }
        }
        const offset = (Math.round(canvas.height * .24) * canvas.width + Math.round(canvas.width * .12)) * 4;
        resolve({ bounds: [minX, minY, maxX, maxY], inside: Array.from(data.slice(offset, offset + 4)) });
      }));
      video.addEventListener('seeked', sample, { once: true }); video.currentTime = 1.5;
    }));
    await expect(window.getByTestId('preview-layer-canvas')).toBeVisible();
    expect(Math.max(...visibleRegion.bounds.map((value, index) => Math.abs(value - [36, 141, 323, 293][index]))))
      .toBeLessThanOrEqual(1);
    expect(Math.max(...visibleRegion.inside.map((value, index) => Math.abs(value - [208, 80, 48, 255][index]))))
      .toBeLessThanOrEqual(7);
    const screenshot = await window.locator('#previewArea').screenshot({ path: testInfo.outputPath('personal-skill-portrait-preview.png') });
    await testInfo.attach('personal-skill-portrait-preview', { body: screenshot, contentType: 'image/png' });

    await window.getByTestId('video-export-button').click();
    await expect(window.getByTestId('video-export-status')).toHaveText('导出完成', { timeout: 60000 });
    const outputPath = (await readScenarioState()).exportOutputPath;
    const { stdout } = await run(ffprobe, ['-v', 'error', '-show_streams', '-show_format', '-of', 'json', outputPath]);
    const probe = JSON.parse(stdout);
    const video = probe.streams.find(stream => stream.codec_type === 'video');
    expect([video.width, video.height]).toEqual([360, 640]);
    expect(Number(probe.format.duration)).toBeCloseTo(3, 1);
    expect(probe.streams.some(stream => stream.codec_type === 'audio')).toBe(true);
    const exportedInside = (await run(ffmpeg, ['-v', 'error', '-ss', '1.5', '-i', outputPath,
      '-vf', 'crop=1:1:43:154,format=rgba', '-frames:v', '1', '-f', 'rawvideo', 'pipe:1'],
    { encoding: 'buffer' })).stdout;
    const exportedOutside = (await run(ffmpeg, ['-v', 'error', '-ss', '1.5', '-i', outputPath,
      '-vf', 'crop=1:1:10:10,format=rgba', '-frames:v', '1', '-f', 'rawvideo', 'pipe:1'],
    { encoding: 'buffer' })).stdout;
    expect(Math.max(...Array.from(exportedInside.subarray(0, 3)).map((value, index) =>
      Math.abs(value - [208, 80, 48][index])))).toBeLessThanOrEqual(7);
    expect(Array.from(exportedInside.subarray(0, 3))).not.toEqual(Array.from(exportedOutside.subarray(0, 3)));

    const beforeReload = portraitSnapshot.document;
    await window.reload();
    await window.waitForFunction(() => window.projectEditingState === 'ready');
    expect((await window.evaluate(() => projectEditing.load(getActiveProjectId()))).document).toEqual(beforeReload);
    await window.getByTestId('request-status-summary').last().click();
    await window.getByTestId('request-status-card').last().getByTestId('subtitle-undo').click();
    expect((await window.evaluate(() => projectEditing.load(getActiveProjectId()))).document.edits).toHaveLength(0);
  });
});

async function bankDialogScreenshot(window, testInfo, name) {
  return window.getByTestId('personal-skills-dialog').screenshot({ path: testInfo.outputPath(name) });
}
