const { test, expect } = require('./electron.fixture');
const { execFile } = require('node:child_process');
const { promisify } = require('node:util');
const fs = require('node:fs/promises');
const run = promisify(execFile);
const ffmpeg = '/opt/homebrew/opt/ffmpeg-full/bin/ffmpeg';
const ffprobe = '/opt/homebrew/opt/ffmpeg-full/bin/ffprobe';

test.describe('formal glass card + local media (fixed translation, real render)', () => {
  test.use({ localCliMode: 'two', localCliEffectResult: 'remotion-media-card-flow', remotionRendering: true });
  test.setTimeout(240000);
  test('imports image/video, refreshes preview assets, persists, exports and undoes one request', async ({ window, electronContext, readScenarioState }, testInfo) => {
    const source = testInfo.outputPath('source.mp4');
    const image = testInfo.outputPath('picture.png');
    const video = testInfo.outputPath('inset.mp4');
    await run(ffmpeg, ['-v','error','-f','lavfi','-i','testsrc2=s=640x360:r=24:d=4',
      '-f','lavfi','-i','sine=frequency=880:duration=4','-shortest','-c:v','libx264','-pix_fmt','yuv420p','-c:a','aac',source]);
    await run(ffmpeg, ['-v','error','-f','lavfi','-i','color=c=0x36BD84:s=200x120','-frames:v','1',image]);
    await run(ffmpeg, ['-v','error','-f','lavfi','-i','testsrc2=s=200x120:r=30:d=4',
      '-f','lavfi','-i','sine=frequency=220:duration=4','-shortest','-c:v','libx264','-pix_fmt','yuv420p','-c:a','aac',video]);
    await window.getByTestId('local-cli-codex').click();
    await window.getByTestId('continue').click();
    await window.getByTestId('video-input').setInputFiles(source);
    await window.getByTestId('start-editing').click();
    await expect(window.locator('#remotionPreview')).toHaveAttribute('data-state', 'ready');
    await expect(window.getByTestId('project-media-import')).toBeVisible();
    await electronContext.electronApp.evaluate(({ app }, paths) => { app.__srtE2EState.mediaImportPaths = paths; }, [image, video]);
    await window.getByTestId('project-media-import').click();
    await expect(window.getByTestId('project-media-select').locator('option')).toHaveCount(3);
    const assets = await window.evaluate(() => window.projectAssetsController.list());
    expect(assets.map(a => a.kind).sort()).toEqual(['image','video']);
    expect(JSON.stringify(assets)).not.toContain(testInfo.outputDir);
    await window.locator('.input-editor').fill('固定测试：粉色玻璃卡片放图片与视频，标题说明标签');
    await window.locator('#generateBtn').click();
    await expect(window.getByTestId('request-status-card').last().getByTestId('timeline-status')).toHaveAttribute('data-state','success');
    await expect(window.locator('#remotionPreview')).toHaveAttribute('data-state','ready');
    await window.evaluate(() => window.editorPlayback.seekSeconds(1));
    await expect(window.locator('#remotionPreview [data-glass-surface]')).toHaveCount(1);
    await expect(window.locator('#remotionPreview img[data-media-asset]')).toHaveCount(1);
    const before = await window.evaluate(() => projectEditing.load(getActiveProjectId()));
    await window.locator('#remotionPreview').screenshot({path:testInfo.outputPath('formal-image-card.png')});
    await window.evaluate(() => window.editorPlayback.seekSeconds(3));
    await expect(window.locator('#remotionPreview [data-media-kind="video"] video')).toHaveCount(1);
    expect(await window.locator('#remotionPreview [data-media-kind="video"] video').evaluate(el => el.muted)).toBe(true);
    await window.locator('#remotionPreview').screenshot({path:testInfo.outputPath('formal-video-card.png')});
    await window.reload();
    await expect(window.locator('#remotionPreview')).toHaveAttribute('data-state','ready');
    await expect(window.getByTestId('project-media-select').locator('option')).toHaveCount(3);
    expect(await window.evaluate(() => projectEditing.load(getActiveProjectId()).document)).toEqual(before.document);
    const movedImage = testInfo.outputPath('temporarily-moved-picture.png');
    await fs.rename(image, movedImage);
    await window.getByTestId('video-export-button').click();
    await expect(window.getByTestId('video-export-status')).toContainText('素材文件已移动');
    await window.reload();
    await expect(window.locator('#remotionPreview')).toHaveAttribute('data-state', 'error');
    await expect(window.locator('#remotionPreviewMessage')).toContainText('素材文件已移动');
    expect(await window.evaluate(() => projectEditing.load(getActiveProjectId()).document)).toEqual(before.document);
    await fs.rename(movedImage, image);
    await window.reload();
    await expect(window.locator('#remotionPreview')).toHaveAttribute('data-state', 'ready');
    await window.getByTestId('video-export-button').click();
    await expect(window.getByTestId('video-export-status')).toHaveText('导出完成',{timeout:180000});
    const output = (await readScenarioState()).exportOutputPath;
    const kept = testInfo.outputPath('formal-media-cards.mp4'); await fs.copyFile(output, kept);
    const {stdout} = await run(ffprobe,['-v','error','-show_streams','-of','json',kept]);
    expect(JSON.parse(stdout).streams.map(s=>s.codec_type)).toEqual(expect.arrayContaining(['video','audio']));
    await testInfo.attach('formal-media-cards',{path:kept,contentType:'video/mp4'});
    await window.getByTestId('request-status-summary').last().click();
    await window.getByTestId('subtitle-undo').last().click();
    await expect.poll(()=>window.evaluate(()=>projectEditing.load(getActiveProjectId()).document.edits.length)).toBe(0);
    await expect(window.locator('#remotionPreview')).toHaveAttribute('data-state','ready');
    expect((await window.evaluate(()=>window.projectAssetsController.list())).length).toBe(2);
    await fs.rename(image,testInfo.outputPath('moved-picture.png'));
    await window.locator('.input-editor').fill('素材移动后的卡片请求');
    await window.locator('#generateBtn').click();
    const failed=window.getByTestId('request-status-card').last();
    await expect(failed.getByTestId('timeline-status')).toHaveAttribute('data-state','failed');
    await expect(failed.locator('.request-error')).toContainText('素材');
    expect(await window.evaluate(()=>projectEditing.load(getActiveProjectId()).document.edits)).toHaveLength(0);
  });
});
